# Generated by Django 5.2.5 on 2025-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nf',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
